import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Join Me",
  description: "Not generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="RLaDbymtiz85N_-W3sx_eDr8-RpHbl5C601y-R59tIE"
        />
      </head>
      <Head>
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <meta
          name="google-site-verification"
          content="RLaDbymtiz85N_-W3sx_eDr8-RpHbl5C601y-R59tIE"
        />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
